SELECT
    b.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * s.SALES) TOTAL_SALES
FROM
   (SELECT *
    FROM
        BOOK_SALES
    WHERE
        SALES_DATE BETWEEN TO_DATE('2022-01-01','yyyy-mm-dd') AND TO_DATE('2022-01-31','yyyy-mm-dd')
   ) s
JOIN 
    BOOK b ON s.BOOK_ID = b.BOOK_ID
JOIN
    AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
GROUP BY
    b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY
    b.AUTHOR_ID, b.CATEGORY DESC