SELECT p.PRODUCT_CODE, p.PRICE * s.SALES_AMOUNT AS PRICE
FROM
   (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) s
JOIN PRODUCT p ON s.PRODUCT_ID = p.PRODUCT_ID
ORDER BY PRICE DESC, p.PRODUCT_CODE
