-- 코드를 입력하세요
SELECT
    TO_CHAR(SALES_DATE,'yyyy-mm-dd') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM 
    ONLINE_SALE 
WHERE
    SALES_DATE >= TO_DATE('2022-03', 'yyyy-mm') AND
    SALES_DATE < TO_DATE('2022-04', 'yyyy-mm')

UNION ALL

SELECT
    TO_CHAR(SALES_DATE,'yyyy-mm-dd') AS SALES_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM 
    OFFLINE_SALE
WHERE
    SALES_DATE >= TO_DATE('2022-03', 'yyyy-mm') AND
    SALES_DATE < TO_DATE('2022-04', 'yyyy-mm')

ORDER BY 
    SALES_DATE, PRODUCT_ID, USER_ID