SELECT ANIMAL_ID, NAME
FROM
    (SELECT i.ANIMAL_ID, i.NAME, (o.DATETIME - i.DATETIME) AS DATETIME
    FROM ANIMAL_INS i JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID)
ORDER BY DATETIME DESC
FETCH FIRST 2 ROWS ONLY