SELECT ROUND(SUM(i.LENGTH) / COUNT(i.ID),2) AS AVERAGE_LENGTH
FROM (SELECT 
         ID,
         CASE
             WHEN LENGTH IS NULL THEN 10
             WHEN LENGTH <= 10 THEN 10
             ELSE LENGTH
         END AS LENGTH
     FROM FISH_INFO) AS i