SELECT i.ANIMAL_ID,	i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE (i.SEX_UPON_INTAKE = 'Intact Male' OR i.SEX_UPON_INTAKE = 'Intact Female') AND
      (o.SEX_UPON_OUTCOME = 'Neutered Male' OR o.SEX_UPON_OUTCOME = 'Spayed Female')
ORDER BY i.ANIMAL_ID    