SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT s.USER_ID) AS USERS
FROM
    ONLINE_SALE s
JOIN
    USER_INFO u ON s.USER_ID = u.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
ORDER BY
    YEAR, MONTH, GENDER