-- 코드를 입력하세요
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CD,
    CATEGORY,
    PRICE
FROM    
    FOOD_PRODUCT f,
    (SELECT
        MAX(PRICE) AS M
    FROM
        FOOD_PRODUCT)
WHERE
    f.PRICE = M