SELECT
    i.COUNT AS FISH_COUNT,
    n.FISH_NAME 
FROM
    FISH_NAME_INFO n
JOIN 
    (SELECT 
            FISH_TYPE, 
            COUNT(ID) AS COUNT
     FROM FISH_INFO
     GROUP BY FISH_TYPE) AS i
ON i.FISH_TYPE = n.FISH_TYPE
ORDER BY FISH_COUNT DESC