SELECT
    COALESCE(i.COUNT, 0) AS FISH_COUNT,
    n.FISH_NAME 
FROM
    FISH_NAME_INFO n
LEFT JOIN 
    (SELECT FISH_TYPE, COUNT(*) AS COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE) AS i
ON i.FISH_TYPE = n.FISH_TYPE
ORDER BY FISH_COUNT DESC