SELECT
    YEAR,
    MONTH,
    PURCHASED_USERS,
    ROUND(PURCHASED_USERS / (SELECT COUNT(USER_ID)
                             FROM USER_INFO 
                             WHERE EXTRACT(YEAR FROM JOINED) = 2021
         ), 1) AS PUCHASED_RATIO
FROM 
  (SELECT 
        EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
        EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
        COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE s
    WHERE EXISTS 
       (SELECT i.USER_ID
        FROM USER_INFO i
        WHERE EXTRACT(YEAR FROM i.JOINED) = 2021 AND i.USER_ID = s.USER_ID
       )
    GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
   ) 
 ORDER BY YEAR, MONTH