WITH RECURSIVE GENERATION_TREE AS (
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM
        ECOLI_DATA
    WHERE
        PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT 
        n.ID,
        n.PARENT_ID,
        t.GENERATION + 1 AS GENERATION
    FROM
        ECOLI_DATA n
    JOIN
        GENERATION_TREE t ON n.PARENT_ID = t.ID
)

SELECT
    COUNT(*) AS COUNT,
    p.GENERATION
FROM
    GENERATION_TREE p
WHERE NOT EXISTS (
    SELECT
        PARENT_ID
    FROM
        GENERATION_TREE c
    WHERE 
        p.ID = c.PARENT_ID
)
GROUP BY
    GENERATION
ORDER BY
    GENERATION