SELECT 
    CONCAT((CEIL(EXTRACT(MONTH FROM DIFFERENTIATION_DATE) / 3)), 'Q') AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY CONCAT((CEIL(EXTRACT(MONTH FROM DIFFERENTIATION_DATE) / 3)), 'Q')
ORDER BY QUARTER;
