SELECT *
FROM
   (SELECT NAME, DATETIME
    FROM ANIMAL_INS i
    WHERE NOT EXISTS
       (SELECT ANIMAL_ID
        FROM ANIMAL_OUTS o
        WHERE i.ANIMAL_ID = o.ANIMAL_ID)
    ORDER BY DATETIME)
WHERE ROWNUM <= 3