SELECT 
    p.PRODUCT_ID, 
    p.PRODUCT_NAME, 
    p.PRICE * o.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT p 
JOIN 
   (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER 
    WHERE PRODUCE_DATE BETWEEN TO_DATE('2022-05-01','yyyy-mm-dd') AND TO_DATE('2022-05-31','yyyy-mm-dd')
    GROUP BY PRODUCT_ID) o
ON p.PRODUCT_ID = o.PRODUCT_ID 
ORDER BY
    TOTAL_SALES DESC, p.PRODUCT_ID
