WITH 
S AS (
    SELECT 1- DISCOUNT_RATE / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'
),
M AS (
    SELECT 1- DISCOUNT_RATE / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'
),
L AS (
    SELECT 1- DISCOUNT_RATE / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'
)
SELECT
    h.HISTORY_ID,
    CASE
        WHEN END_DATE - START_DATE + 1 >= 90 THEN c.DAILY_FEE * (END_DATE - START_DATE + 1) * (SELECT DISCOUNT_RATE FROM L)
        WHEN END_DATE - START_DATE + 1 >= 30 THEN c.DAILY_FEE * (END_DATE - START_DATE + 1) * (SELECT DISCOUNT_RATE FROM M)
        WHEN END_DATE - START_DATE + 1 >= 7 THEN c.DAILY_FEE * (END_DATE - START_DATE + 1) * (SELECT DISCOUNT_RATE FROM S)
        ELSE c.DAILY_FEE * (END_DATE - START_DATE + 1)
    END AS FEE
FROM
    (SELECT HISTORY_ID, CAR_ID ,START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) h
JOIN 
    (SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭') c
ON h.CAR_ID = c.CAR_ID
ORDER BY FEE DESC, h.HISTORY_ID DESC