SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM 
    (SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
    FROM APPOINTMENT
    WHERE 
        TO_CHAR(APNT_YMD,'yyyy-mm-dd') = '2022-04-13' AND
        APNT_CNCL_YN = 'N') a
JOIN PATIENT p ON a.PT_NO = p.PT_NO
JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
ORDER BY a.APNT_YMD

    