WITH HOURS AS (
    SELECT LEVEL -1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
),
COUNTS AS (
    SELECT 
        TO_NUMBER(TO_CHAR(DATETIME, 'hh24')) AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'hh24'))
)
SELECT
    h.HOUR AS HOUR,
    NVL(c.COUNT, 0) AS COUNT
FROM
    HOURS h LEFT JOIN COUNTS c ON h.HOUR = c.HOUR 
ORDER BY
    HOUR