SELECT
    HOUR,
    COUNT
FROM
   (SELECT
        COUNT(*) AS COUNT,
        TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
    FROM
        ANIMAL_OUTS
    GROUP BY
        TO_NUMBER(TO_CHAR(DATETIME, 'HH24')))
WHERE
    HOUR >= 9 AND HOUR < 20
ORDER BY
    HOUR
    
