SELECT
    p.MEMBER_NAME,
    r.REVIEW_TEXT,
    TO_CHAR(r.REVIEW_DATE, 'yyyy-mm-dd') AS REVIEW_DATE
FROM
   (SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(MEMBER_ID) =  
        (SELECT MAX(COUNT)
         FROM
           (SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID)
        )
    ) m
JOIN MEMBER_PROFILE p ON m.MEMBER_ID = p.MEMBER_ID
JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
ORDER BY
    REVIEW_DATE, r.REVIEW_TEXT


        