SELECT
    f.ID,
    n.FISH_NAME,
    f.LENGTH
FROM
    FISH_INFO f
JOIN (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM
        FISH_INFO
    GROUP BY
        FISH_TYPE
) m
ON f.FISH_TYPE = m.FISH_TYPE AND f.LENGTH = m.MAX_LENGTH
JOIN FISH_NAME_INFO n
    ON f.FISH_TYPE = n.FISH_TYPE
ORDER BY
    f.ID;
