-- 코드를 입력하세요
SELECT
    BOOK_ID,
    TO_CHAR(PUBLISHED_DATE,'yyyy-mm-dd') AS PUBLISHED_DATE
FROM 
    BOOK
WHERE
    PUBLISHED_DATE BETWEEN TO_DATE('2021-01-01', 'yyyy-mm-dd') AND TO_DATE('2021-12-31', 'yyyy-mm-dd')
    AND
    CATEGORY = '인문'
ORDER BY
    PUBLISHED_DATE