WITH HIGHEST_GRADE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    HAVING SCORE = (
        SELECT MAX(SUM_SCORE)
        FROM
           (SELECT SUM(SCORE) AS SUM_SCORE
            FROM HR_GRADE
            WHERE YEAR = 2022
            GROUP BY EMP_NO) AS s
    )
)
SELECT
    h.SCORE,
    e.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM HR_EMPLOYEES e
JOIN HIGHEST_GRADE h ON e.EMP_NO = h.EMP_NO
