-- 코드를 입력하세요
SELECT 
    b.TITLE,
    b.BOARD_ID,
    r.REPLY_ID,
    r.WRITER_ID,
    r.CONTENTS,
    TO_CHAR(r.CREATED_DATE,'yyyy-mm-dd') AS CREATED_DATE
FROM 
    USED_GOODS_BOARD b
JOIN 
    USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE BETWEEN TO_DATE('2022-10-01','yyyy-mm-dd') AND TO_DATE('2022-10-31','yyyy-mm-dd')
ORDER BY r.CREATED_DATE, b.TITLE