SELECT
    d.DEPT_ID,
    d.DEPT_NAME_EN,
    ROUND(e.SUM_SAL / COUNT) AS AVG_SAL
FROM
   (SELECT DEPT_ID, SUM(SAL) AS SUM_SAL, COUNT(*) AS COUNT
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID) e
JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID
ORDER BY AVG_SAL DESC