SELECT
    COUNT(i.LENGTH) AS FISH_COUNT,
    MAX(i.LENGTH) AS MAX_LENGTH,
    i.FISH_TYPE
FROM 
   (SELECT
    ID,
    FISH_TYPE,
    CASE
        WHEN LENGTH > 10 THEN LENGTH
        WHEN LENGTH IS NULL THEN 10
        ELSE 10
    END AS LENGTH
    FROM FISH_INFO) i
GROUP BY i.FISH_TYPE
HAVING (SUM(i.LENGTH) / COUNT(i.LENGTH)) >= 33
ORDER BY i.FISH_TYPE