WITH FRONT_END_CODE AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PYTHON_CODE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
C_SHARP_CODE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
)
SELECT
    CASE
        WHEN d.SKILL_CODE & f.CODE != 0 AND d.SKILL_CODE & p.CODE != 0 THEN 'A'
        WHEN d.SKILL_CODE & c.CODE != 0 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    d.ID,
    d.EMAIL
FROM DEVELOPERS d, FRONT_END_CODE f, PYTHON_CODE p, C_SHARP_CODE c
WHERE d.SKILL_CODE & f.CODE != 0 OR d.SKILL_CODE & c.CODE != 0
ORDER BY GRADE, ID

